version: '3.8'

services:
  # Coin Chat Agent - Mastra web interface
  coin-chat-agent:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://127.0.0.1:11434/api
      - MODEL_NAME_AT_ENDPOINT=qwen2.5:1.5b
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - mastra-db:/app/mastra.db
    profiles:
      - web
      - mastra
      - default
    restart: unless-stopped
    command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Ollama LLM Service (for local development)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    volumes:
      - ollama-data:/root/.ollama
    profiles:
      - ollama
      - local-llm
    restart: unless-stopped
    command: >
      sh -c "ollama serve & 
             sleep 10 && 
             ollama pull qwen2.5:1.5b && 
             tail -f /dev/null"

volumes:
  mastra-db:
    driver: local
  ollama-data:
    driver: local
